name: Elixir CI

on: push

jobs:
  test:
    runs-on: ubuntu-18.04

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: stevencwarren_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1.0.0
      - uses: actions/setup-elixir@v1.0.0
        with:
          otp-version: 22.x
          elixir-version: 1.9.x
      - run: MIX_ENV=test DATABASE_URL=postgres://postgres:postgres@localhost/stevencwarren_test:${{ job.services.postgres.ports[5432] }}  mix deps.get
      - run: MIX_ENV=test DATABASE_URL=postgres://postgres:postgres@localhost/stevencwarren_test:${{ job.services.postgres.ports[5432] }}  mix ecto.create
      - run: MIX_ENV=test DATABASE_URL=postgres://postgres:postgres@localhost/stevencwarren_test:${{ job.services.postgres.ports[5432] }}  mix ecto.migrate
      - run: MIX_ENV=test DATABASE_URL=postgres://postgres:postgres@localhost/stevencwarren_test:${{ job.services.postgres.ports[5432] }}  mix test
